spring:
  application:
    name: YourMeal
  profiles:
    active: prod
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 15MB
  liquibase:
    enabled: true
    change-log: /db/changelog/db.changelog-master.yaml
app:
  log-mode: true
# AMAZON WEB SERVICES CONFIGURATIONS --------

---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/yourmeal
    username: postgres
    password: abbos2004postgresql
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    open-in-view: false
  h2:
    console:
      enabled: false
server:
  port: 8080
